# Generated by Django 6.0.1 on 2026-01-08 20:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='salary_base',
        ),
        migrations.AddField(
            model_name='provider',
            name='advance_enabled',
            field=models.BooleanField(default=True, verbose_name='Recebe Adiantamento Quinzenal'),
        ),
        migrations.AddField(
            model_name='provider',
            name='advance_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Percentual do adiantamento quinzenal (ex: 40%)', max_digits=5, verbose_name='Percentual de Adiantamento'),
        ),
        migrations.AddField(
            model_name='provider',
            name='monthly_hours',
            field=models.IntegerField(default=220, help_text='Horas de trabalho por mês (padrão: 220h)', verbose_name='Carga Horária Mensal'),
        ),
        migrations.AddField(
            model_name='provider',
            name='monthly_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor mensal acordado no contrato PJ', max_digits=10, verbose_name='Valor Mensal Contratado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='vt_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo mensal do vale transporte', max_digits=10, verbose_name='Valor Vale Transporte'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bank_agency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('TED', 'TED'), ('TRANSFER', 'Bank Transfer')], default='PIX', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Função/Cargo'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.CharField(help_text='Formato: MM/YYYY (ex: 01/2026)', max_length=7, verbose_name='Mês de Referência')),
                ('base_value', models.DecimalField(decimal_places=2, help_text='Valor mensal do contrato', max_digits=10, verbose_name='Valor Base Mensal')),
                ('hourly_rate', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automaticamente', max_digits=10, verbose_name='Valor por Hora')),
                ('advance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Adiantamento Quinzenal')),
                ('remaining_value', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automaticamente', max_digits=10, verbose_name='Saldo Após Adiantamento')),
                ('overtime_hours_50', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas extras com 50% de adicional', max_digits=10, verbose_name='Horas Extras 50%')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas trabalhadas em feriados (100% adicional)', max_digits=10, verbose_name='Horas em Feriados')),
                ('night_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas com adicional noturno (20%)', max_digits=10, verbose_name='Horas Noturnas')),
                ('late_minutes', models.IntegerField(default=0, help_text='Total de minutos de atraso no mês', verbose_name='Minutos de Atraso')),
                ('absence_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas de Falta')),
                ('manual_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outros descontos a serem aplicados', max_digits=10, verbose_name='Descontos Manuais')),
                ('vt_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor mensal do VT', max_digits=10, verbose_name='Vale Transporte')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Horas Extras')),
                ('holiday_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Feriados')),
                ('dsr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='DSR')),
                ('night_shift_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Adicional Noturno')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total de Proventos')),
                ('late_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Desconto Atrasos')),
                ('absence_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Desconto Faltas')),
                ('dsr_on_absences', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='DSR sobre Faltas')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total de Descontos')),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Bruto')),
                ('net_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Líquido')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CLOSED', 'Fechada'), ('PAID', 'Paga')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Observações e anotações sobre esta folha', null=True, verbose_name='Observações')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='api.provider', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-reference_month', 'provider__name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.payroll', verbose_name='Folha de Pagamento')),
            ],
            options={
                'verbose_name': 'Item da Folha',
                'verbose_name_plural': 'Itens da Folha',
                'ordering': ['type', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['provider', 'reference_month'], name='api_payroll_provide_64d3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='api_payroll_status_83f917_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('provider', 'reference_month')},
        ),
    ]
