# Generated by Django 6.0.1 on 2026-01-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_provider_options_remove_provider_salary_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='dsr_on_absences',
        ),
    ]
