"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure--egnau4+aixm^=vk3f3^xx2zf4wrn34vlq_i913^0+5k$5nt7o"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "").split(",") if os.getenv("ALLOWED_HOSTS") else []
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "corsheaders",
    "django_filters",
    "site_manage",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": os.environ.get("DB_PORT", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Custom User Model
AUTH_USER_MODEL = "site_manage.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173"
).split(",")

# Permitir envio de cookies e credenciais
CORS_ALLOW_CREDENTIALS = True

# Headers permitidos
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "site_manage.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 10,  # Default page size
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Sistema de Gestão de Pagamentos PJ - API",
    "DESCRIPTION": """
# Sistema de Folha de Pagamento para Prestadores PJ

Este sistema gerencia o cálculo de pagamentos para prestadores **Pessoa Jurídica (PJ)** 
com regras contratuais customizadas que incluem:

- ✅ Horas extras (50% adicional)
- ✅ Horas em feriados (100% adicional)  
- ✅ Adicional noturno (20%)
- ✅ DSR (Descanso Semanal Remunerado)
- ✅ Descontos (atrasos, faltas, vale transporte)
- ✅ Adiantamento quinzenal

## Fórmulas de Cálculo

### Valor da Hora
```
valor_hora = valor_contrato_mensal ÷ 220
```

### Adiantamento Quinzenal (padrão 40%)
```
adiantamento = valor_contrato_mensal × 0.40
```

### Horas Extras 50%
```
valor_hora_extra = valor_hora × 1.5
total_horas_extras = horas_extras × valor_hora_extra
```

### Horas em Feriado (100%)
```
valor_hora_feriado = valor_hora × 2.0
total_feriados = horas_feriado × valor_hora_feriado
```

### DSR (16.67%)
```
dsr = total_horas_extras × 0.1667
```

### Adicional Noturno (20%)
```
adicional_noturno = horas_noturnas × (valor_hora × 0.20)
```

### Valor Final
```
proventos = saldo_base + horas_extras + feriados + dsr + adicional_noturno
descontos = atrasos + faltas + dsr_sobre_faltas + vt + manuais
líquido = proventos - descontos
```

## Autenticação

⚠️ **Nota**: Autenticação será implementada em fase futura. 
Por enquanto, todos os endpoints estão abertos para desenvolvimento.
    """,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {"name": "Equipe de Desenvolvimento", "email": "dev@payroll-system.com"},
    "LICENSE": {"name": "Proprietary"},
    "TAGS": [
        {"name": "providers", "description": "Gerenciamento de prestadores PJ"},
        {
            "name": "payrolls",
            "description": "Folhas de pagamento com cálculos automáticos",
        },
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# JWT AUTHENTICATION CONFIGURATION
# ==============================================================================


# Update REST_FRAMEWORK to include custom JWT authentication from cookies
REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
    "site_manage.authentication.JWTCookieAuthentication",  # Custom class that reads from cookies AND header
]
REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"] = [
    "rest_framework.permissions.IsAuthenticated",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        hours=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_HOURS", "1"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": False,  # Desabilitado para evitar refresh excessivo
    "BLACKLIST_AFTER_ROTATION": False,
    # Cookie-based authentication para persistência de sessão
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_SECURE": os.getenv("JWT_COOKIE_SECURE", "False") == "True",
    "AUTH_COOKIE_HTTP_ONLY": True,  # Protege contra XSS
    "AUTH_COOKIE_SAMESITE": os.getenv("JWT_COOKIE_SAMESITE", "Lax"),
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_DOMAIN": None,
}

# Configuração de timeout de inatividade (padrão: 300 segundos = 5 minutos)
SESSION_INACTIVITY_TIMEOUT = 300  # segundos
