# Generated by Django 6.0.2 on 2026-02-19 16:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='e.g. 01/2026', max_length=50)),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_calculated', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.CharField(help_text='Formato: MM/YYYY (ex: 01/2026)', max_length=7, verbose_name='Mês de Referência')),
                ('hired_date', models.DateField(blank=True, help_text='Se preenchido, calcula salário proporcional aos dias trabalhados', null=True, verbose_name='Data de Admissão/Início no Mês')),
                ('worked_days', models.IntegerField(default=0, editable=False, help_text='Calculado automaticamente se hired_date preenchido (0 = mês completo)', verbose_name='Dias Trabalhados')),
                ('proportional_base_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automaticamente se hired_date preenchido', max_digits=10, verbose_name='Salário Base Proporcional')),
                ('base_value', models.DecimalField(decimal_places=2, help_text='Valor mensal do contrato', max_digits=10, verbose_name='Valor Base Mensal')),
                ('hourly_rate', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automaticamente', max_digits=10, verbose_name='Valor por Hora')),
                ('advance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Adiantamento Quinzenal')),
                ('remaining_value', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automaticamente', max_digits=10, verbose_name='Saldo Após Adiantamento')),
                ('overtime_hours_50', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas extras com 50% de adicional', max_digits=10, verbose_name='Horas Extras 50%')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas trabalhadas em feriados (100% adicional)', max_digits=10, verbose_name='Horas em Feriados')),
                ('night_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas com adicional noturno (20%)', max_digits=10, verbose_name='Horas Noturnas')),
                ('late_minutes', models.IntegerField(default=0, help_text='Total de minutos de atraso no mês', verbose_name='Minutos de Atraso')),
                ('absence_days', models.IntegerField(default=0, help_text='Número de dias de falta no mês (para cálculo de VT e desconto)', verbose_name='Dias de Falta')),
                ('absence_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DEPRECATED: Use absence_days. Mantido para compatibilidade.', max_digits=10, verbose_name='Horas de Falta')),
                ('manual_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outros descontos a serem aplicados', max_digits=10, verbose_name='Descontos Manuais')),
                ('vt_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automaticamente: viagens × tarifa × dias trabalhados', max_digits=10, verbose_name='Vale Transporte Calculado')),
                ('vt_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DEPRECATED: Use vt_value. Mantido para compatibilidade.', max_digits=10, verbose_name='Desconto Vale Transporte')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Horas Extras')),
                ('holiday_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Feriados')),
                ('dsr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='DSR')),
                ('night_shift_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Adicional Noturno')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total de Proventos')),
                ('late_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Desconto Atrasos')),
                ('absence_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Desconto Faltas')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total de Descontos')),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Bruto')),
                ('net_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor Líquido')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CLOSED', 'Fechada'), ('PAID', 'Paga')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Observações e anotações sobre esta folha', null=True, verbose_name='Observações')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-reference_month', 'provider__name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='% Hora Extra')),
                ('night_shift_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='% Adicional Noturno')),
                ('holiday_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='% Feriado')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='% Adiantamento Padrão')),
                ('transport_voucher_type', models.CharField(choices=[('FIXED', 'Valor Fixo Mensal'), ('DYNAMIC_PER_DAY', 'Dinâmico por Dias Trabalhados'), ('DYNAMIC_PER_TRIP', 'Dinâmico por Viagem Realizada')], default='DYNAMIC_PER_TRIP', max_length=20, verbose_name='Tipo de Vale Transporte')),
                ('business_days_rule', models.CharField(choices=[('WORKALENDAR', 'Calendário Brasileiro Oficial'), ('FIXED_30', 'Fixo 30 Dias')], default='WORKALENDAR', max_length=20, verbose_name='Regra de Dias Úteis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Folha',
                'verbose_name_plural': 'Configurações de Folha',
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Item da Folha',
                'verbose_name_plural': 'Itens da Folha',
                'ordering': ['type', 'description'],
            },
        ),
        migrations.CreateModel(
            name='PayrollMathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='% Hora Extra')),
                ('night_shift_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='% Adicional Noturno')),
                ('holiday_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='% Feriado')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='% Adiantamento Padrão')),
                ('transport_voucher_type', models.CharField(choices=[('FIXED', 'Valor Fixo Mensal'), ('DYNAMIC_PER_DAY', 'Dinâmico por Dias Trabalhados'), ('DYNAMIC_PER_TRIP', 'Dinâmico por Viagem Realizada')], default='DYNAMIC_PER_TRIP', max_length=20, verbose_name='Tipo de Vale Transporte')),
                ('business_days_rule', models.CharField(choices=[('WORKALENDAR', 'Calendário Brasileiro Oficial'), ('FIXED_30', 'Fixo 30 Dias')], default='WORKALENDAR', max_length=20, verbose_name='Regra de Dias Úteis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Template de Cálculo',
                'verbose_name_plural': 'Templates de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document', models.CharField(blank=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos)', max_length=14, null=True, verbose_name='CPF/CNPJ')),
                ('role', models.CharField(max_length=100, verbose_name='Função/Cargo')),
                ('monthly_value', models.DecimalField(decimal_places=2, help_text='Valor mensal acordado no contrato PJ', max_digits=10, verbose_name='Valor Mensal Contratado')),
                ('monthly_hours', models.IntegerField(default=220, help_text='Horas de trabalho por mês (padrão: 220h)', verbose_name='Carga Horária Mensal')),
                ('advance_enabled', models.BooleanField(default=True, verbose_name='Recebe Adiantamento Quinzenal')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Percentual do adiantamento quinzenal (ex: 40%)', max_digits=5, verbose_name='Percentual de Adiantamento')),
                ('vt_enabled', models.BooleanField(default=False, help_text='Se True, VT será calculado automaticamente com base nos dias trabalhados', verbose_name='Recebe Vale Transporte')),
                ('vt_fare', models.DecimalField(decimal_places=2, default=Decimal('4.60'), help_text='Valor da passagem de ônibus (ex: R$ 4,60 em Belém)', max_digits=5, verbose_name='Tarifa da Passagem')),
                ('vt_trips_per_day', models.IntegerField(default=4, help_text='Número de viagens de ônibus por dia (ex: 2, 4, 6, etc.)', verbose_name='Viagens por Dia')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('TED', 'TED'), ('TRANSFER', 'Bank Transfer')], default='PIX', max_length=20, verbose_name='Método de Pagamento')),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('bank_agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['name'],
            },
        ),
    ]
