# Generated by Django 6.0.1 on 2026-01-22 01:18

from site_manage import models
from site_manage.models import CustomUserManager
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da Empresa"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_month",
                    models.CharField(
                        help_text="Formato: MM/YYYY (ex: 01/2026)",
                        max_length=7,
                        verbose_name="Mês de Referência",
                    ),
                ),
                (
                    "base_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor mensal do contrato",
                        max_digits=10,
                        verbose_name="Valor Base Mensal",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automaticamente",
                        max_digits=10,
                        verbose_name="Valor por Hora",
                    ),
                ),
                (
                    "advance_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Adiantamento Quinzenal",
                    ),
                ),
                (
                    "remaining_value",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automaticamente",
                        max_digits=10,
                        verbose_name="Saldo Após Adiantamento",
                    ),
                ),
                (
                    "overtime_hours_50",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Horas extras com 50% de adicional",
                        max_digits=10,
                        verbose_name="Horas Extras 50%",
                    ),
                ),
                (
                    "holiday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Horas trabalhadas em feriados (100% adicional)",
                        max_digits=10,
                        verbose_name="Horas em Feriados",
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Horas com adicional noturno (20%)",
                        max_digits=10,
                        verbose_name="Horas Noturnas",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Total de minutos de atraso no mês",
                        verbose_name="Minutos de Atraso",
                    ),
                ),
                (
                    "absence_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Horas de Falta",
                    ),
                ),
                (
                    "manual_discounts",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outros descontos a serem aplicados",
                        max_digits=10,
                        verbose_name="Descontos Manuais",
                    ),
                ),
                (
                    "vt_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor mensal do VT",
                        max_digits=10,
                        verbose_name="Vale Transporte",
                    ),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Valor Horas Extras",
                    ),
                ),
                (
                    "holiday_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Valor Feriados",
                    ),
                ),
                (
                    "dsr_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="DSR",
                    ),
                ),
                (
                    "night_shift_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Adicional Noturno",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Total de Proventos",
                    ),
                ),
                (
                    "late_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Desconto Atrasos",
                    ),
                ),
                (
                    "absence_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Desconto Faltas",
                    ),
                ),
                (
                    "total_discounts",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Total de Descontos",
                    ),
                ),
                (
                    "gross_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Valor Bruto",
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="Valor Líquido",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("CLOSED", "Fechada"),
                            ("PAID", "Paga"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações e anotações sobre esta folha",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Fechamento"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Folha de Pagamento",
                "verbose_name_plural": "Folhas de Pagamento",
                "ordering": ["-reference_month", "provider__name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("CUSTOMER_ADMIN", "Customer Admin"),
                            ("PROVIDER", "Provider"),
                        ],
                        default="PROVIDER",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "inactivity_timeout",
                    models.IntegerField(
                        default=300,
                        help_text="Tempo de inatividade antes do logout automático (segundos)",
                        verbose_name="Timeout de Inatividade",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa do usuário (null para Super Admin)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["username"],
            },
            managers=[
                ("objects", CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CREDIT", "Crédito"), ("DEBIT", "Débito")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll",
                        verbose_name="Folha de Pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Folha",
                "verbose_name_plural": "Itens da Folha",
                "ordering": ["type", "description"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("role", models.CharField(max_length=100, verbose_name="Função/Cargo")),
                (
                    "monthly_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor mensal acordado no contrato PJ",
                        max_digits=10,
                        verbose_name="Valor Mensal Contratado",
                    ),
                ),
                (
                    "monthly_hours",
                    models.IntegerField(
                        default=220,
                        help_text="Horas de trabalho por mês (padrão: 220h)",
                        verbose_name="Carga Horária Mensal",
                    ),
                ),
                (
                    "advance_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Recebe Adiantamento Quinzenal"
                    ),
                ),
                (
                    "advance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        help_text="Percentual do adiantamento quinzenal (ex: 40%)",
                        max_digits=5,
                        verbose_name="Percentual de Adiantamento",
                    ),
                ),
                (
                    "vt_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor fixo mensal do vale transporte",
                        max_digits=10,
                        verbose_name="Valor Vale Transporte",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("TED", "TED"),
                            ("TRANSFER", "Bank Transfer"),
                        ],
                        default="PIX",
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "pix_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chave PIX"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "bank_agency",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Conta"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa proprietária deste prestador",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuário associado ao prestador (para login)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestador",
                "verbose_name_plural": "Prestadores",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="payroll",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="provider",
                verbose_name="Prestador",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(help_text="e.g. 01/2026", max_length=50),
                ),
                ("amount_base", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_calculated",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="provider",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["provider", "reference_month"],
                name="api_payroll_provide_64d3fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(fields=["status"], name="api_payroll_status_83f917_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("provider", "reference_month")},
        ),
    ]
