# Generated by Django 6.0.2 on 2026-02-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_manage', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfiguration',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='site_manage.payroll', verbose_name='Folha de Pagamento'),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(help_text='Empresa proprietária deste prestador', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuário associado ao prestador (para login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='site_manage.provider', verbose_name='Prestador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='site_manage.provider'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['provider', 'reference_month'], name='site_manage_provide_bff34e_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='site_manage_status_c4c52f_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status', 'created_at'], name='site_manage_status_fb7616_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['reference_month', 'status'], name='site_manage_referen_357e10_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['-created_at'], name='site_manage_created_f0b347_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('provider', 'reference_month')},
        ),
    ]
