# Generated by Django 5.2.10 on 2026-01-27 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
            ],
            options={
                'verbose_name': 'Token de Reset de Senha',
                'verbose_name_plural': 'Tokens de Reset de Senha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='site_manage_provide_bff34e_idx',
            old_name='api_payroll_provide_64d3fa_idx',
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='site_manage_status_c4c52f_idx',
            old_name='api_payroll_status_83f917_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='site_manage.provider'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='site_manage.provider', verbose_name='Prestador'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='site_manage.payroll', verbose_name='Folha de Pagamento'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(help_text='Empresa proprietária deste prestador', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='site_manage.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa do usuário (null para Super Admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='site_manage.company', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status', 'created_at'], name='site_manage_status_fb7616_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['reference_month', 'status'], name='site_manage_referen_357e10_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['-created_at'], name='site_manage_created_f0b347_idx'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='site_manage_token_867aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', '-created_at'], name='site_manage_user_id_6cbc14_idx'),
        ),
    ]
