# Generated by Django 6.0.2 on 2026-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmathtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, este é o template inalterável usado como base para cálculos.', verbose_name='Template Padrão Sistema'),
        ),
    ]
