# Generated by Django 5.2.10 on 2026-02-03 13:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0002_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='hired_date',
            field=models.DateField(blank=True, help_text='Se preenchido, calcula salário proporcional aos dias trabalhados', null=True, verbose_name='Data de Admissão/Início no Mês'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='proportional_base_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automaticamente se hired_date preenchido', max_digits=10, verbose_name='Salário Base Proporcional'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='worked_days',
            field=models.IntegerField(default=0, editable=False, help_text='Calculado automaticamente se hired_date preenchido (0 = mês completo)', verbose_name='Dias Trabalhados'),
        ),
    ]
