# Generated by Django 5.2.11 on 2026-02-08 02:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0004_add_vt_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollMathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('overtime_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='% Hora Extra')),
                ('night_shift_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='% Adicional Noturno')),
                ('holiday_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='% Feriado')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='% Adiantamento Padrão')),
                ('transport_voucher_type', models.CharField(choices=[('FIXED', 'Valor Fixo Mensal'), ('DYNAMIC_PER_DAY', 'Dinâmico por Dias Trabalhados'), ('DYNAMIC_PER_TRIP', 'Dinâmico por Viagem Realizada')], default='DYNAMIC_PER_TRIP', max_length=20, verbose_name='Tipo de Vale Transporte')),
                ('business_days_rule', models.CharField(choices=[('WORKALENDAR', 'Calendário Brasileiro Oficial'), ('FIXED_30', 'Fixo 30 Dias')], default='WORKALENDAR', max_length=20, verbose_name='Regra de Dias Úteis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Cálculo',
                'verbose_name_plural': 'Templates de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='% Hora Extra')),
                ('night_shift_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='% Adicional Noturno')),
                ('holiday_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='% Feriado')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='% Adiantamento Padrão')),
                ('transport_voucher_type', models.CharField(choices=[('FIXED', 'Valor Fixo Mensal'), ('DYNAMIC_PER_DAY', 'Dinâmico por Dias Trabalhados'), ('DYNAMIC_PER_TRIP', 'Dinâmico por Viagem Realizada')], default='DYNAMIC_PER_TRIP', max_length=20, verbose_name='Tipo de Vale Transporte')),
                ('business_days_rule', models.CharField(choices=[('WORKALENDAR', 'Calendário Brasileiro Oficial'), ('FIXED_30', 'Fixo 30 Dias')], default='WORKALENDAR', max_length=20, verbose_name='Regra de Dias Úteis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='site_manage.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Folha',
                'verbose_name_plural': 'Configurações de Folha',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic (5 Prestadores)'), ('PRO', 'Pro (20 Prestadores)'), ('ENTERPRISE', 'Enterprise (100 Prestadores)'), ('UNLIMITED', 'Unlimited (Ilimitado)')], default='BASIC', max_length=20, verbose_name='Plano')),
                ('max_providers', models.IntegerField(help_text='Máximo de prestadores ativos permitidos', verbose_name='Limite de Prestadores')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor mensal cobrado', max_digits=10, verbose_name='Preço da Assinatura (R$)')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término (Null = Vitalício)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Assinatura Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='site_manage.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
