# Generated by Django 5.2.11 on 2026-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0005_payrollmathtemplate_payrollconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='document',
            field=models.CharField(blank=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos)', max_length=14, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('TRIAL', 'Trial (90 Dias)'), ('BASIC', 'Basic (5 Prestadores)'), ('PRO', 'Pro (20 Prestadores)'), ('ENTERPRISE', 'Enterprise (100 Prestadores)'), ('UNLIMITED', 'Unlimited (Ilimitado)')], default='BASIC', max_length=20, verbose_name='Plano'),
        ),
    ]
